name: Docker build and push

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build . --tag gh-az-runner
    - name: Create artefacts
      run: docker save gh-az-runner > gh-az-runner.tar
    - name: Upload artefacts
      uses: actions/upload-artifact@v4
      with:
        name: gh-az-runner
        path: gh-az-runner.tar
        retention-days: 1 # Delete artefacts after 1 day

  ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: build
    env:
      IMAGE_ID: ghcr.io/contoso-lri/gh-az-runner
      VERSION: ${{ vars.GH_RUNNER_VERSION }}
    steps:
    - name: Download artefacts
      uses: actions/download-artifact@v4
      with:
        name: gh-az-runner
    - name: Load artefacts
      run: docker load < gh-az-runner.tar
    - name: Log in to GH Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push to GH Container registry
      run: |
        IMAGE_ID="ghcr.io/contoso-lri/gh-az-runner"
        VERSION=${{ vars.GH_RUNNER_VERSION }}
        docker tag gh-az-runner:latest $IMAGE_ID:latest
        docker tag gh-az-runner:latest $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:latest
        docker push $IMAGE_ID:$VERSION

  dockerio:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    env:
      IMAGE_ID: "lrivallain/gh-az-runner"
      VERSION: ${{ vars.GH_RUNNER_VERSION }}
    steps:
    - name: Download artefacts
      uses: actions/download-artifact@v4
      with:
        name: gh-az-runner
    - name: Load artefacts
      run: docker load < gh-az-runner.tar
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push to Docker Hub
      run: |
        docker tag gh-az-runner:latest $IMAGE_ID:latest
        docker tag gh-az-runner:latest $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:latest
        docker push $IMAGE_ID:$VERSION